# Generated by Django 2.2.6 on 2022-08-24 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0004_auto_20220819_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receita',
            old_name='puplicada',
            new_name='publicada',
        ),
    ]
