# Generated by Django 2.2.6 on 2022-09-13 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0007_auto_20220913_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='foto_receita',
        ),
    ]
