# Generated by Django 2.2.6 on 2022-09-13 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0011_receita_foto_receita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='foto_receita',
            field=models.ImageField(blank=True, upload_to='<django.db.models.fields.CharField>/fotos/%d/%m/%Y'),
        ),
    ]
