# Generated by Django 2.2.6 on 2022-09-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0012_auto_20220913_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='foto_receita',
            field=models.ImageField(blank=True, upload_to='<bound method Field.get_attname of <django.db.models.fields.CharField>>/fotos/%d/%m/%Y'),
        ),
    ]
