# Generated by Django 2.2.6 on 2022-09-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0015_auto_20220913_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='nome_receita',
            field=models.CharField(max_length=200),
        ),
    ]
